# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

trigger:
- none

variables:
  IISWebsiteName: 'test.zakat.icclmd.org'

resources:
  pipelines:
     - pipeline: 'buildPipeline'
       project: 'zakat.icclmd.org'
       source: 'Build Pipeline'
       branch: 'master'

stages:
  - stage: DeployWebsite
    displayName: 'Deploy Website'
    pool:
      vmImage: windows-latest

    jobs:
    - deployment: DeployWebsite
      displayName: 'Deploy Website'
      environment: 'Windows 11 Test Server.DESKTOP-CLFU8GS'
      strategy:
        runOnce:
          deploy:
            steps:
              - checkout: none

              - download: 'buildPipeline'
                name: 'DownloadBuildArtifacts'
                displayName: 'Download Build Artifacts'
                artifact: 'zakat.icclmd.org'
                
              - task: IISWebAppManagementOnMachineGroup@0
                name: 'StopIIS'
                displayName: 'Stop IIS Website'
                inputs:
                  IISDeploymentType: 'IISWebsite'
                  ActionIISWebsite: 'StopWebsite'
                  StartStopWebsiteName: '${{ variables.IISWebsiteName }}'
              
              - script: echo $(Pipeline.Workspace)\buildPipeline\test.zakat.icclmd.org

              - task: IISWebAppDeploymentOnMachineGroup@0
                name: 'DeployIIS'
                displayName: 'Deploy IIS Website'
                inputs:
                  WebSiteName: '${{ variables.IISWebsiteName }}'
                  Package: '$(Pipeline.Worspace)\buildPipeline\test.zakat.icclmd.org'
                  TakeAppOfflineFlag: true
              
              - task: IISWebAppManagementOnMachineGroup@0
                name: 'StartIIS'
                displayName: 'Start IIS Website'
                inputs:
                  IISDeploymentType: 'IISWebsite'
                  ActionIISWebsite: 'StartWebsite'
                  StartStopWebsiteName: '${{ variables.IISWebsiteName }}'