# ASP.NET
# Build and test ASP.NET projects.
# Add steps that publish symbols, save build artifacts, deploy, and more:
# https://docs.microsoft.com/azure/devops/pipelines/apps/aspnet/build-aspnet-4

trigger:
# - master
  - none

variables:
  IISWebsiteName: 'zakat.icclmd.org'
  solution: '**/*.sln'
  project: '**/*.vbproj'
  buildPlatform: 'Any CPU'
  buildConfiguration: 'Release'

resources:
  pipelines:
     - pipeline: 'buildPipeline'
       project: 'zakat.icclmd.org'
       source: 'Build Pipeline'
       branch: 'master'

stages:
  - stage: DeployWebsite
    displayName: 'Deploy Website'
    pool:
      vmImage: 'windows-latest'

    jobs:
    - deployment: DeployWebsite
      displayName: 'Deploy Website'
      
steps:
- task: NuGetToolInstaller@1
  name: 'NuGetToolInstaller'
  displayName: 'NuGet tool installer'

- task: NuGetCommand@2
  inputs:
    command: 'restore' 
    restoreSolution: '$(solution)'
    feedsToUse: 'select'

- task: VSBuild@1
  inputs:
    solution: '$(solution)'
    msbuildArgs: '/p:DeployOnBuild=true /p:WebPublishMethod=Package /p:PackageAsSingleFile=true /p:SkipInvalidConfigurations=true /p:PackageLocation="$(build.artifactStagingDirectory)"'
    platform: '$(buildPlatform)'
    configuration: '$(buildConfiguration)'

- task: VSTest@2
  inputs:
    platform: '$(buildPlatform)'
    configuration: '$(buildConfiguration)'
