'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated from a template.
'
'     Manual changes to this file may cause unexpected behavior in your application.
'     Manual changes to this file will be overwritten if the code is regenerated.
' </auto-generated>
'------------------------------------------------------------------------------

Imports System
Imports System.Collections.Generic

Partial Public Class APPLICATION
    Public Property applicationId As Integer
    Public Property userId As Nullable(Of Integer)
    Public Property organizationId As Nullable(Of Integer)
    Public Property isSubmitted As Nullable(Of Boolean)
    Public Property isValidated As Nullable(Of Boolean)
    Public Property isInvestigated As Nullable(Of Boolean)
    Public Property isQualified As Nullable(Of Boolean)
    Public Property approvalStatus As String
    Public Property createdOn As Nullable(Of Date)
    Public Property createdBy As Nullable(Of Integer)
    Public Property updatedOn As Nullable(Of Date)
    Public Property updatedBy As Nullable(Of Integer)

    Public Overridable Property ORGANIZATION As ORGANIZATION
    Public Overridable Property USER As USER

End Class
