'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated from a template.
'
'     Manual changes to this file may cause unexpected behavior in your application.
'     Manual changes to this file will be overwritten if the code is regenerated.
' </auto-generated>
'------------------------------------------------------------------------------

Imports System
Imports System.Collections.Generic

Partial Public Class ARTIFACT
    Public Property artifactId As Integer
    Public Property artifactTypeId As Nullable(Of Integer)
    Public Property applicationId As Nullable(Of Integer)
    Public Property filename As String
    Public Property contentType As String
    Public Property data As Byte()

    Public Overridable Property ARTIFACT_TYPE As ARTIFACT_TYPE
    Public Overridable Property APPLICATION As APPLICATION

End Class
