'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated by a tool.
'
'     Changes to this file may cause incorrect behavior and will be lost if
'     the code is regenerated. 
' </auto-generated>
'------------------------------------------------------------------------------

Option Strict On
Option Explicit On


Partial Public Class Confirm
    
    '''<summary>
    '''lblFirstName control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblFirstName As Global.System.Web.UI.WebControls.Label
    
    '''<summary>
    '''lblYear1 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblYear1 As Global.System.Web.UI.WebControls.Label
    
    '''<summary>
    '''lblMemberId control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblMemberId As Global.System.Web.UI.WebControls.Label
    
    '''<summary>
    '''lblFullName control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblFullName As Global.System.Web.UI.WebControls.Label
    
    '''<summary>
    '''lblMemberType control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblMemberType As Global.System.Web.UI.WebControls.Label
    
    '''<summary>
    '''lblYear2 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblYear2 As Global.System.Web.UI.WebControls.Label
    
    '''<summary>
    '''lblPayAmount control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblPayAmount As Global.System.Web.UI.WebControls.Label
    
    '''<summary>
    '''lblPayDate control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblPayDate As Global.System.Web.UI.WebControls.Label
    
    '''<summary>
    '''lblPayMethod control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblPayMethod As Global.System.Web.UI.WebControls.Label
    
    '''<summary>
    '''lblReference control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblReference As Global.System.Web.UI.WebControls.Label
    
    '''<summary>
    '''lblRecordedBy control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblRecordedBy As Global.System.Web.UI.WebControls.Label
    
    '''<summary>
    '''btnProfile control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents btnProfile As Global.System.Web.UI.WebControls.LinkButton
End Class
