'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated by a tool.
'
'     Changes to this file may cause incorrect behavior and will be lost if
'     the code is regenerated. 
' </auto-generated>
'------------------------------------------------------------------------------

Option Strict On
Option Explicit On


Partial Public Class Dashboard

  '''<summary>
  '''phChartRow1Left control.
  '''</summary>
  '''<remarks>
  '''Auto-generated field.
  '''To modify move field declaration from designer file to code-behind file.
  '''</remarks>
  Protected WithEvents phChartRow1Left As Global.System.Web.UI.WebControls.PlaceHolder

  '''<summary>
  '''divTitle control.
  '''</summary>
  '''<remarks>
  '''Auto-generated field.
  '''To modify move field declaration from designer file to code-behind file.
  '''</remarks>
  Protected WithEvents divTitle As Global.System.Web.UI.HtmlControls.HtmlGenericControl

  '''<summary>
  '''drpApplicationsByGenderByYear control.
  '''</summary>
  '''<remarks>
  '''Auto-generated field.
  '''To modify move field declaration from designer file to code-behind file.
  '''</remarks>
  Protected WithEvents drpApplicationsByGenderByYear As Global.System.Web.UI.WebControls.DropDownList

  '''<summary>
  '''phChartRow1Right control.
  '''</summary>
  '''<remarks>
  '''Auto-generated field.
  '''To modify move field declaration from designer file to code-behind file.
  '''</remarks>
  Protected WithEvents phChartRow1Right As Global.System.Web.UI.WebControls.PlaceHolder

  '''<summary>
  '''div1 control.
  '''</summary>
  '''<remarks>
  '''Auto-generated field.
  '''To modify move field declaration from designer file to code-behind file.
  '''</remarks>
  Protected WithEvents div1 As Global.System.Web.UI.HtmlControls.HtmlGenericControl

  '''<summary>
  '''drpApplicationsByGenderByNationalityByYear control.
  '''</summary>
  '''<remarks>
  '''Auto-generated field.
  '''To modify move field declaration from designer file to code-behind file.
  '''</remarks>
  Protected WithEvents drpApplicationsByGenderByNationalityByYear As Global.System.Web.UI.WebControls.DropDownList

  '''<summary>
  '''phChartRow2Left control.
  '''</summary>
  '''<remarks>
  '''Auto-generated field.
  '''To modify move field declaration from designer file to code-behind file.
  '''</remarks>
  Protected WithEvents phChartRow2Left As Global.System.Web.UI.WebControls.PlaceHolder

  '''<summary>
  '''phChartRow2Right control.
  '''</summary>
  '''<remarks>
  '''Auto-generated field.
  '''To modify move field declaration from designer file to code-behind file.
  '''</remarks>
  Protected WithEvents phChartRow2Right As Global.System.Web.UI.WebControls.PlaceHolder

  '''<summary>
  '''div2 control.
  '''</summary>
  '''<remarks>
  '''Auto-generated field.
  '''To modify move field declaration from designer file to code-behind file.
  '''</remarks>
  Protected WithEvents div2 As Global.System.Web.UI.HtmlControls.HtmlGenericControl

  '''<summary>
  '''drpAverageProcessingDaysByMonth control.
  '''</summary>
  '''<remarks>
  '''Auto-generated field.
  '''To modify move field declaration from designer file to code-behind file.
  '''</remarks>
  Protected WithEvents drpAverageProcessingDaysByMonth As Global.System.Web.UI.WebControls.DropDownList

  '''<summary>
  '''phChartRow3Left control.
  '''</summary>
  '''<remarks>
  '''Auto-generated field.
  '''To modify move field declaration from designer file to code-behind file.
  '''</remarks>
  Protected WithEvents phChartRow3Left As Global.System.Web.UI.WebControls.PlaceHolder

  '''<summary>
  '''div3 control.
  '''</summary>
  '''<remarks>
  '''Auto-generated field.
  '''To modify move field declaration from designer file to code-behind file.
  '''</remarks>
  Protected WithEvents div3 As Global.System.Web.UI.HtmlControls.HtmlGenericControl

  '''<summary>
  '''drpTotalDispersedByMonth control.
  '''</summary>
  '''<remarks>
  '''Auto-generated field.
  '''To modify move field declaration from designer file to code-behind file.
  '''</remarks>
  Protected WithEvents drpTotalDispersedByMonth As Global.System.Web.UI.WebControls.DropDownList

  '''<summary>
  '''phChartRow4Left control.
  '''</summary>
  '''<remarks>
  '''Auto-generated field.
  '''To modify move field declaration from designer file to code-behind file.
  '''</remarks>
  Protected WithEvents phChartRow4Left As Global.System.Web.UI.WebControls.PlaceHolder
End Class
