'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated by a tool.
'
'     Changes to this file may cause incorrect behavior and will be lost if
'     the code is regenerated. 
' </auto-generated>
'------------------------------------------------------------------------------

Option Strict On
Option Explicit On


Partial Public Class Discussion

  '''<summary>
  '''pnlNavigateShow control.
  '''</summary>
  '''<remarks>
  '''Auto-generated field.
  '''To modify move field declaration from designer file to code-behind file.
  '''</remarks>
  Protected WithEvents pnlNavigateShow As Global.System.Web.UI.WebControls.Panel

  '''<summary>
  '''btnCollapse control.
  '''</summary>
  '''<remarks>
  '''Auto-generated field.
  '''To modify move field declaration from designer file to code-behind file.
  '''</remarks>
  Protected WithEvents btnCollapse As Global.System.Web.UI.WebControls.LinkButton

  '''<summary>
  '''btnCreatePost control.
  '''</summary>
  '''<remarks>
  '''Auto-generated field.
  '''To modify move field declaration from designer file to code-behind file.
  '''</remarks>
  Protected WithEvents btnCreatePost As Global.System.Web.UI.WebControls.LinkButton

  '''<summary>
  '''txtSearch control.
  '''</summary>
  '''<remarks>
  '''Auto-generated field.
  '''To modify move field declaration from designer file to code-behind file.
  '''</remarks>
  Protected WithEvents txtSearch As Global.System.Web.UI.WebControls.TextBox

  '''<summary>
  '''rptCategories control.
  '''</summary>
  '''<remarks>
  '''Auto-generated field.
  '''To modify move field declaration from designer file to code-behind file.
  '''</remarks>
  Protected WithEvents rptCategories As Global.System.Web.UI.WebControls.Repeater

  '''<summary>
  '''pnlNavigateHide control.
  '''</summary>
  '''<remarks>
  '''Auto-generated field.
  '''To modify move field declaration from designer file to code-behind file.
  '''</remarks>
  Protected WithEvents pnlNavigateHide As Global.System.Web.UI.WebControls.Panel

  '''<summary>
  '''btnExpand control.
  '''</summary>
  '''<remarks>
  '''Auto-generated field.
  '''To modify move field declaration from designer file to code-behind file.
  '''</remarks>
  Protected WithEvents btnExpand As Global.System.Web.UI.WebControls.LinkButton

  '''<summary>
  '''pnlBody control.
  '''</summary>
  '''<remarks>
  '''Auto-generated field.
  '''To modify move field declaration from designer file to code-behind file.
  '''</remarks>
  Protected WithEvents pnlBody As Global.System.Web.UI.WebControls.Panel

  '''<summary>
  '''pnlLanding control.
  '''</summary>
  '''<remarks>
  '''Auto-generated field.
  '''To modify move field declaration from designer file to code-behind file.
  '''</remarks>
  Protected WithEvents pnlLanding As Global.System.Web.UI.WebControls.Panel

  '''<summary>
  '''pnlSearch control.
  '''</summary>
  '''<remarks>
  '''Auto-generated field.
  '''To modify move field declaration from designer file to code-behind file.
  '''</remarks>
  Protected WithEvents pnlSearch As Global.System.Web.UI.WebControls.Panel

  '''<summary>
  '''lblKeywordSearch control.
  '''</summary>
  '''<remarks>
  '''Auto-generated field.
  '''To modify move field declaration from designer file to code-behind file.
  '''</remarks>
  Protected WithEvents lblKeywordSearch As Global.System.Web.UI.WebControls.Label

  '''<summary>
  '''lblSearchResults control.
  '''</summary>
  '''<remarks>
  '''Auto-generated field.
  '''To modify move field declaration from designer file to code-behind file.
  '''</remarks>
  Protected WithEvents lblSearchResults As Global.System.Web.UI.WebControls.Label

  '''<summary>
  '''pnlNoSearchMsg control.
  '''</summary>
  '''<remarks>
  '''Auto-generated field.
  '''To modify move field declaration from designer file to code-behind file.
  '''</remarks>
  Protected WithEvents pnlNoSearchMsg As Global.System.Web.UI.WebControls.Panel

  '''<summary>
  '''lblNoSearchMsg control.
  '''</summary>
  '''<remarks>
  '''Auto-generated field.
  '''To modify move field declaration from designer file to code-behind file.
  '''</remarks>
  Protected WithEvents lblNoSearchMsg As Global.System.Web.UI.WebControls.Label

  '''<summary>
  '''rptSearchResultsDisplay control.
  '''</summary>
  '''<remarks>
  '''Auto-generated field.
  '''To modify move field declaration from designer file to code-behind file.
  '''</remarks>
  Protected WithEvents rptSearchResultsDisplay As Global.System.Web.UI.WebControls.Repeater

  '''<summary>
  '''pnlCategories control.
  '''</summary>
  '''<remarks>
  '''Auto-generated field.
  '''To modify move field declaration from designer file to code-behind file.
  '''</remarks>
  Protected WithEvents pnlCategories As Global.System.Web.UI.WebControls.Panel

  '''<summary>
  '''lblCategory control.
  '''</summary>
  '''<remarks>
  '''Auto-generated field.
  '''To modify move field declaration from designer file to code-behind file.
  '''</remarks>
  Protected WithEvents lblCategory As Global.System.Web.UI.WebControls.Label

  '''<summary>
  '''lblCategoryResults control.
  '''</summary>
  '''<remarks>
  '''Auto-generated field.
  '''To modify move field declaration from designer file to code-behind file.
  '''</remarks>
  Protected WithEvents lblCategoryResults As Global.System.Web.UI.WebControls.Label

  '''<summary>
  '''pnlNoPostCategoryMsg control.
  '''</summary>
  '''<remarks>
  '''Auto-generated field.
  '''To modify move field declaration from designer file to code-behind file.
  '''</remarks>
  Protected WithEvents pnlNoPostCategoryMsg As Global.System.Web.UI.WebControls.Panel

  '''<summary>
  '''lblNoPostCategoryMsg control.
  '''</summary>
  '''<remarks>
  '''Auto-generated field.
  '''To modify move field declaration from designer file to code-behind file.
  '''</remarks>
  Protected WithEvents lblNoPostCategoryMsg As Global.System.Web.UI.WebControls.Label

  '''<summary>
  '''rptPostCategories control.
  '''</summary>
  '''<remarks>
  '''Auto-generated field.
  '''To modify move field declaration from designer file to code-behind file.
  '''</remarks>
  Protected WithEvents rptPostCategories As Global.System.Web.UI.WebControls.Repeater

  '''<summary>
  '''pnlPosts control.
  '''</summary>
  '''<remarks>
  '''Auto-generated field.
  '''To modify move field declaration from designer file to code-behind file.
  '''</remarks>
  Protected WithEvents pnlPosts As Global.System.Web.UI.WebControls.Panel

  '''<summary>
  '''lblPosts control.
  '''</summary>
  '''<remarks>
  '''Auto-generated field.
  '''To modify move field declaration from designer file to code-behind file.
  '''</remarks>
  Protected WithEvents lblPosts As Global.System.Web.UI.WebControls.Label

  '''<summary>
  '''lblPostResults control.
  '''</summary>
  '''<remarks>
  '''Auto-generated field.
  '''To modify move field declaration from designer file to code-behind file.
  '''</remarks>
  Protected WithEvents lblPostResults As Global.System.Web.UI.WebControls.Label

  '''<summary>
  '''rptPosts control.
  '''</summary>
  '''<remarks>
  '''Auto-generated field.
  '''To modify move field declaration from designer file to code-behind file.
  '''</remarks>
  Protected WithEvents rptPosts As Global.System.Web.UI.WebControls.Repeater

  '''<summary>
  '''lblModalHeader control.
  '''</summary>
  '''<remarks>
  '''Auto-generated field.
  '''To modify move field declaration from designer file to code-behind file.
  '''</remarks>
  Protected WithEvents lblModalHeader As Global.System.Web.UI.WebControls.Label

  '''<summary>
  '''txtPostTitle control.
  '''</summary>
  '''<remarks>
  '''Auto-generated field.
  '''To modify move field declaration from designer file to code-behind file.
  '''</remarks>
  Protected WithEvents txtPostTitle As Global.System.Web.UI.WebControls.TextBox

  '''<summary>
  '''valPostTitle control.
  '''</summary>
  '''<remarks>
  '''Auto-generated field.
  '''To modify move field declaration from designer file to code-behind file.
  '''</remarks>
  Protected WithEvents valPostTitle As Global.System.Web.UI.WebControls.RequiredFieldValidator

  '''<summary>
  '''drpPostCategory control.
  '''</summary>
  '''<remarks>
  '''Auto-generated field.
  '''To modify move field declaration from designer file to code-behind file.
  '''</remarks>
  Protected WithEvents drpPostCategory As Global.System.Web.UI.WebControls.DropDownList

  '''<summary>
  '''valPostCategory control.
  '''</summary>
  '''<remarks>
  '''Auto-generated field.
  '''To modify move field declaration from designer file to code-behind file.
  '''</remarks>
  Protected WithEvents valPostCategory As Global.System.Web.UI.WebControls.RequiredFieldValidator

  '''<summary>
  '''txtPostContent control.
  '''</summary>
  '''<remarks>
  '''Auto-generated field.
  '''To modify move field declaration from designer file to code-behind file.
  '''</remarks>
  Protected WithEvents txtPostContent As Global.System.Web.UI.WebControls.TextBox

  '''<summary>
  '''valPostContent control.
  '''</summary>
  '''<remarks>
  '''Auto-generated field.
  '''To modify move field declaration from designer file to code-behind file.
  '''</remarks>
  Protected WithEvents valPostContent As Global.System.Web.UI.WebControls.RequiredFieldValidator

  '''<summary>
  '''divNotLoggedInPost control.
  '''</summary>
  '''<remarks>
  '''Auto-generated field.
  '''To modify move field declaration from designer file to code-behind file.
  '''</remarks>
  Protected WithEvents divNotLoggedInPost As Global.System.Web.UI.HtmlControls.HtmlGenericControl

  '''<summary>
  '''btnLogInPost control.
  '''</summary>
  '''<remarks>
  '''Auto-generated field.
  '''To modify move field declaration from designer file to code-behind file.
  '''</remarks>
  Protected WithEvents btnLogInPost As Global.System.Web.UI.WebControls.Button

  '''<summary>
  '''btnSubmitPost control.
  '''</summary>
  '''<remarks>
  '''Auto-generated field.
  '''To modify move field declaration from designer file to code-behind file.
  '''</remarks>
  Protected WithEvents btnSubmitPost As Global.System.Web.UI.WebControls.Button
End Class
