'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated by a tool.
'
'     Changes to this file may cause incorrect behavior and will be lost if
'     the code is regenerated. 
' </auto-generated>
'------------------------------------------------------------------------------

Option Strict On
Option Explicit On


Partial Public Class Feedback

  '''<summary>
  '''txtFirstName control.
  '''</summary>
  '''<remarks>
  '''Auto-generated field.
  '''To modify move field declaration from designer file to code-behind file.
  '''</remarks>
  Protected WithEvents txtFirstName As Global.System.Web.UI.WebControls.TextBox

  '''<summary>
  '''txtLastName control.
  '''</summary>
  '''<remarks>
  '''Auto-generated field.
  '''To modify move field declaration from designer file to code-behind file.
  '''</remarks>
  Protected WithEvents txtLastName As Global.System.Web.UI.WebControls.TextBox

  '''<summary>
  '''txtEmail control.
  '''</summary>
  '''<remarks>
  '''Auto-generated field.
  '''To modify move field declaration from designer file to code-behind file.
  '''</remarks>
  Protected WithEvents txtEmail As Global.System.Web.UI.WebControls.TextBox

  '''<summary>
  '''RegularExpressionValidator1 control.
  '''</summary>
  '''<remarks>
  '''Auto-generated field.
  '''To modify move field declaration from designer file to code-behind file.
  '''</remarks>
  Protected WithEvents RegularExpressionValidator1 As Global.System.Web.UI.WebControls.RegularExpressionValidator

  '''<summary>
  '''txtPhone control.
  '''</summary>
  '''<remarks>
  '''Auto-generated field.
  '''To modify move field declaration from designer file to code-behind file.
  '''</remarks>
  Protected WithEvents txtPhone As Global.System.Web.UI.WebControls.TextBox

  '''<summary>
  '''MaskedEditExtender1 control.
  '''</summary>
  '''<remarks>
  '''Auto-generated field.
  '''To modify move field declaration from designer file to code-behind file.
  '''</remarks>
  Protected WithEvents MaskedEditExtender1 As Global.AjaxControlToolkit.MaskedEditExtender

  '''<summary>
  '''chkFollowUp control.
  '''</summary>
  '''<remarks>
  '''Auto-generated field.
  '''To modify move field declaration from designer file to code-behind file.
  '''</remarks>
  Protected WithEvents chkFollowUp As Global.System.Web.UI.WebControls.CheckBox

  '''<summary>
  '''lblRatingSatisfaction control.
  '''</summary>
  '''<remarks>
  '''Auto-generated field.
  '''To modify move field declaration from designer file to code-behind file.
  '''</remarks>
  Protected WithEvents lblRatingSatisfaction As Global.System.Web.UI.WebControls.Label

  '''<summary>
  '''drpRatingSatisfaction control.
  '''</summary>
  '''<remarks>
  '''Auto-generated field.
  '''To modify move field declaration from designer file to code-behind file.
  '''</remarks>
  Protected WithEvents drpRatingSatisfaction As Global.System.Web.UI.WebControls.DropDownList

  '''<summary>
  '''valRatingSatisfaction control.
  '''</summary>
  '''<remarks>
  '''Auto-generated field.
  '''To modify move field declaration from designer file to code-behind file.
  '''</remarks>
  Protected WithEvents valRatingSatisfaction As Global.System.Web.UI.WebControls.RequiredFieldValidator

  '''<summary>
  '''lblRatingRecommendation control.
  '''</summary>
  '''<remarks>
  '''Auto-generated field.
  '''To modify move field declaration from designer file to code-behind file.
  '''</remarks>
  Protected WithEvents lblRatingRecommendation As Global.System.Web.UI.WebControls.Label

  '''<summary>
  '''drpRatingRecommendation control.
  '''</summary>
  '''<remarks>
  '''Auto-generated field.
  '''To modify move field declaration from designer file to code-behind file.
  '''</remarks>
  Protected WithEvents drpRatingRecommendation As Global.System.Web.UI.WebControls.DropDownList

  '''<summary>
  '''valRatingRecommendation control.
  '''</summary>
  '''<remarks>
  '''Auto-generated field.
  '''To modify move field declaration from designer file to code-behind file.
  '''</remarks>
  Protected WithEvents valRatingRecommendation As Global.System.Web.UI.WebControls.RequiredFieldValidator

  '''<summary>
  '''lblRatingExperience control.
  '''</summary>
  '''<remarks>
  '''Auto-generated field.
  '''To modify move field declaration from designer file to code-behind file.
  '''</remarks>
  Protected WithEvents lblRatingExperience As Global.System.Web.UI.WebControls.Label

  '''<summary>
  '''drpRatingExperience control.
  '''</summary>
  '''<remarks>
  '''Auto-generated field.
  '''To modify move field declaration from designer file to code-behind file.
  '''</remarks>
  Protected WithEvents drpRatingExperience As Global.System.Web.UI.WebControls.DropDownList

  '''<summary>
  '''valRatingExperience control.
  '''</summary>
  '''<remarks>
  '''Auto-generated field.
  '''To modify move field declaration from designer file to code-behind file.
  '''</remarks>
  Protected WithEvents valRatingExperience As Global.System.Web.UI.WebControls.RequiredFieldValidator

  '''<summary>
  '''lblMostLiked control.
  '''</summary>
  '''<remarks>
  '''Auto-generated field.
  '''To modify move field declaration from designer file to code-behind file.
  '''</remarks>
  Protected WithEvents lblMostLiked As Global.System.Web.UI.WebControls.Label

  '''<summary>
  '''chkMostLiked control.
  '''</summary>
  '''<remarks>
  '''Auto-generated field.
  '''To modify move field declaration from designer file to code-behind file.
  '''</remarks>
  Protected WithEvents chkMostLiked As Global.System.Web.UI.WebControls.CheckBoxList

  '''<summary>
  '''chkOtherMostLiked control.
  '''</summary>
  '''<remarks>
  '''Auto-generated field.
  '''To modify move field declaration from designer file to code-behind file.
  '''</remarks>
  Protected WithEvents chkOtherMostLiked As Global.System.Web.UI.WebControls.CheckBox

  '''<summary>
  '''txtOtherMostLiked control.
  '''</summary>
  '''<remarks>
  '''Auto-generated field.
  '''To modify move field declaration from designer file to code-behind file.
  '''</remarks>
  Protected WithEvents txtOtherMostLiked As Global.System.Web.UI.WebControls.TextBox

  '''<summary>
  '''valOtherMostLiked control.
  '''</summary>
  '''<remarks>
  '''Auto-generated field.
  '''To modify move field declaration from designer file to code-behind file.
  '''</remarks>
  Protected WithEvents valOtherMostLiked As Global.System.Web.UI.WebControls.CustomValidator

  '''<summary>
  '''lblMostToImprove control.
  '''</summary>
  '''<remarks>
  '''Auto-generated field.
  '''To modify move field declaration from designer file to code-behind file.
  '''</remarks>
  Protected WithEvents lblMostToImprove As Global.System.Web.UI.WebControls.Label

  '''<summary>
  '''chkMostToImprove control.
  '''</summary>
  '''<remarks>
  '''Auto-generated field.
  '''To modify move field declaration from designer file to code-behind file.
  '''</remarks>
  Protected WithEvents chkMostToImprove As Global.System.Web.UI.WebControls.CheckBoxList

  '''<summary>
  '''chkOtherMostToImprove control.
  '''</summary>
  '''<remarks>
  '''Auto-generated field.
  '''To modify move field declaration from designer file to code-behind file.
  '''</remarks>
  Protected WithEvents chkOtherMostToImprove As Global.System.Web.UI.WebControls.CheckBox

  '''<summary>
  '''txtOtherMostToImprove control.
  '''</summary>
  '''<remarks>
  '''Auto-generated field.
  '''To modify move field declaration from designer file to code-behind file.
  '''</remarks>
  Protected WithEvents txtOtherMostToImprove As Global.System.Web.UI.WebControls.TextBox

  '''<summary>
  '''valOtherMostLikeToImprove control.
  '''</summary>
  '''<remarks>
  '''Auto-generated field.
  '''To modify move field declaration from designer file to code-behind file.
  '''</remarks>
  Protected WithEvents valOtherMostLikeToImprove As Global.System.Web.UI.WebControls.CustomValidator

  '''<summary>
  '''lblSuggestionsForImprovement control.
  '''</summary>
  '''<remarks>
  '''Auto-generated field.
  '''To modify move field declaration from designer file to code-behind file.
  '''</remarks>
  Protected WithEvents lblSuggestionsForImprovement As Global.System.Web.UI.WebControls.Label

  '''<summary>
  '''txtSuggestionsForImprovement control.
  '''</summary>
  '''<remarks>
  '''Auto-generated field.
  '''To modify move field declaration from designer file to code-behind file.
  '''</remarks>
  Protected WithEvents txtSuggestionsForImprovement As Global.System.Web.UI.WebControls.TextBox

  '''<summary>
  '''lbl control.
  '''</summary>
  '''<remarks>
  '''Auto-generated field.
  '''To modify move field declaration from designer file to code-behind file.
  '''</remarks>
  Protected WithEvents lbl As Global.System.Web.UI.WebControls.Label

  '''<summary>
  '''txtAdditionalComments control.
  '''</summary>
  '''<remarks>
  '''Auto-generated field.
  '''To modify move field declaration from designer file to code-behind file.
  '''</remarks>
  Protected WithEvents txtAdditionalComments As Global.System.Web.UI.WebControls.TextBox

  '''<summary>
  '''btnSubmit control.
  '''</summary>
  '''<remarks>
  '''Auto-generated field.
  '''To modify move field declaration from designer file to code-behind file.
  '''</remarks>
  Protected WithEvents btnSubmit As Global.System.Web.UI.WebControls.Button

  '''<summary>
  '''LabelRating8 control.
  '''</summary>
  '''<remarks>
  '''Auto-generated field.
  '''To modify move field declaration from designer file to code-behind file.
  '''</remarks>
  Protected WithEvents LabelRating8 As Global.AjaxControlToolkit.Rating
End Class
