'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated by a tool.
'
'     Changes to this file may cause incorrect behavior and will be lost if
'     the code is regenerated. 
' </auto-generated>
'------------------------------------------------------------------------------

Option Strict On
Option Explicit On


Partial Public Class OrganizationEdit

  '''<summary>
  '''txtOrganizationName control.
  '''</summary>
  '''<remarks>
  '''Auto-generated field.
  '''To modify move field declaration from designer file to code-behind file.
  '''</remarks>
  Protected WithEvents txtOrganizationName As Global.System.Web.UI.WebControls.TextBox

  '''<summary>
  '''txtOrganizationAbbreviation control.
  '''</summary>
  '''<remarks>
  '''Auto-generated field.
  '''To modify move field declaration from designer file to code-behind file.
  '''</remarks>
  Protected WithEvents txtOrganizationAbbreviation As Global.System.Web.UI.WebControls.TextBox

  '''<summary>
  '''txtEmail control.
  '''</summary>
  '''<remarks>
  '''Auto-generated field.
  '''To modify move field declaration from designer file to code-behind file.
  '''</remarks>
  Protected WithEvents txtEmail As Global.System.Web.UI.WebControls.TextBox

  '''<summary>
  '''valEmailValid control.
  '''</summary>
  '''<remarks>
  '''Auto-generated field.
  '''To modify move field declaration from designer file to code-behind file.
  '''</remarks>
  Protected WithEvents valEmailValid As Global.System.Web.UI.WebControls.RegularExpressionValidator

  '''<summary>
  '''valEmailRequired control.
  '''</summary>
  '''<remarks>
  '''Auto-generated field.
  '''To modify move field declaration from designer file to code-behind file.
  '''</remarks>
  Protected WithEvents valEmailRequired As Global.System.Web.UI.WebControls.RequiredFieldValidator

  '''<summary>
  '''txtPhone control.
  '''</summary>
  '''<remarks>
  '''Auto-generated field.
  '''To modify move field declaration from designer file to code-behind file.
  '''</remarks>
  Protected WithEvents txtPhone As Global.System.Web.UI.WebControls.TextBox

  '''<summary>
  '''txtWebsite control.
  '''</summary>
  '''<remarks>
  '''Auto-generated field.
  '''To modify move field declaration from designer file to code-behind file.
  '''</remarks>
  Protected WithEvents txtWebsite As Global.System.Web.UI.WebControls.TextBox

  '''<summary>
  '''RegularExpressionValidator1 control.
  '''</summary>
  '''<remarks>
  '''Auto-generated field.
  '''To modify move field declaration from designer file to code-behind file.
  '''</remarks>
  Protected WithEvents RegularExpressionValidator1 As Global.System.Web.UI.WebControls.RegularExpressionValidator

  '''<summary>
  '''RequiredFieldValidator1 control.
  '''</summary>
  '''<remarks>
  '''Auto-generated field.
  '''To modify move field declaration from designer file to code-behind file.
  '''</remarks>
  Protected WithEvents RequiredFieldValidator1 As Global.System.Web.UI.WebControls.RequiredFieldValidator

  '''<summary>
  '''txtStreet control.
  '''</summary>
  '''<remarks>
  '''Auto-generated field.
  '''To modify move field declaration from designer file to code-behind file.
  '''</remarks>
  Protected WithEvents txtStreet As Global.System.Web.UI.WebControls.TextBox

  '''<summary>
  '''txtCity control.
  '''</summary>
  '''<remarks>
  '''Auto-generated field.
  '''To modify move field declaration from designer file to code-behind file.
  '''</remarks>
  Protected WithEvents txtCity As Global.System.Web.UI.WebControls.TextBox

  '''<summary>
  '''drpState control.
  '''</summary>
  '''<remarks>
  '''Auto-generated field.
  '''To modify move field declaration from designer file to code-behind file.
  '''</remarks>
  Protected WithEvents drpState As Global.System.Web.UI.WebControls.DropDownList

  '''<summary>
  '''txtZip control.
  '''</summary>
  '''<remarks>
  '''Auto-generated field.
  '''To modify move field declaration from designer file to code-behind file.
  '''</remarks>
  Protected WithEvents txtZip As Global.System.Web.UI.WebControls.TextBox

  '''<summary>
  '''btnCancel control.
  '''</summary>
  '''<remarks>
  '''Auto-generated field.
  '''To modify move field declaration from designer file to code-behind file.
  '''</remarks>
  Protected WithEvents btnCancel As Global.System.Web.UI.WebControls.HyperLink

  '''<summary>
  '''btnSaveOrganization control.
  '''</summary>
  '''<remarks>
  '''Auto-generated field.
  '''To modify move field declaration from designer file to code-behind file.
  '''</remarks>
  Protected WithEvents btnSaveOrganization As Global.System.Web.UI.WebControls.Button
End Class
