'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated by a tool.
'
'     Changes to this file may cause incorrect behavior and will be lost if
'     the code is regenerated. 
' </auto-generated>
'------------------------------------------------------------------------------

Option Strict On
Option Explicit On


Partial Public Class OrganizationProfile

  '''<summary>
  '''lblOrganizationName control.
  '''</summary>
  '''<remarks>
  '''Auto-generated field.
  '''To modify move field declaration from designer file to code-behind file.
  '''</remarks>
  Protected WithEvents lblOrganizationName As Global.System.Web.UI.WebControls.Label

  '''<summary>
  '''hypEmail control.
  '''</summary>
  '''<remarks>
  '''Auto-generated field.
  '''To modify move field declaration from designer file to code-behind file.
  '''</remarks>
  Protected WithEvents hypEmail As Global.System.Web.UI.WebControls.HyperLink

  '''<summary>
  '''lblPhone control.
  '''</summary>
  '''<remarks>
  '''Auto-generated field.
  '''To modify move field declaration from designer file to code-behind file.
  '''</remarks>
  Protected WithEvents lblPhone As Global.System.Web.UI.WebControls.Label

  '''<summary>
  '''hypWebsite control.
  '''</summary>
  '''<remarks>
  '''Auto-generated field.
  '''To modify move field declaration from designer file to code-behind file.
  '''</remarks>
  Protected WithEvents hypWebsite As Global.System.Web.UI.WebControls.HyperLink

  '''<summary>
  '''lblAddress control.
  '''</summary>
  '''<remarks>
  '''Auto-generated field.
  '''To modify move field declaration from designer file to code-behind file.
  '''</remarks>
  Protected WithEvents lblAddress As Global.System.Web.UI.WebControls.Label

  '''<summary>
  '''lblMission control.
  '''</summary>
  '''<remarks>
  '''Auto-generated field.
  '''To modify move field declaration from designer file to code-behind file.
  '''</remarks>
  Protected WithEvents lblMission As Global.System.Web.UI.WebControls.Label

  '''<summary>
  '''ifrMap control.
  '''</summary>
  '''<remarks>
  '''Auto-generated field.
  '''To modify move field declaration from designer file to code-behind file.
  '''</remarks>
  Protected WithEvents ifrMap As Global.System.Web.UI.HtmlControls.HtmlIframe
End Class
