'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated from a template.
'
'     Manual changes to this file may cause unexpected behavior in your application.
'     Manual changes to this file will be overwritten if the code is regenerated.
' </auto-generated>
'------------------------------------------------------------------------------

Imports System
Imports System.Collections.Generic

Partial Public Class POST_CATEGORY
    Public Property postCategoryId As Integer
    Public Property name As String
    Public Property description As String
    Public Property countOfPosts As Integer

    Public Overridable Property POST As ICollection(Of POST) = New HashSet(Of POST)

End Class
