'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated by a tool.
'
'     Changes to this file may cause incorrect behavior and will be lost if
'     the code is regenerated. 
' </auto-generated>
'------------------------------------------------------------------------------

Option Strict On
Option Explicit On


Partial Public Class Profile

  '''<summary>
  '''lblPageHeaderUserFullName control.
  '''</summary>
  '''<remarks>
  '''Auto-generated field.
  '''To modify move field declaration from designer file to code-behind file.
  '''</remarks>
  Protected WithEvents lblPageHeaderUserFullName As Global.System.Web.UI.WebControls.Label

  '''<summary>
  '''Form control.
  '''</summary>
  '''<remarks>
  '''Auto-generated field.
  '''To modify move field declaration from designer file to code-behind file.
  '''</remarks>
  Protected WithEvents Form As Global.System.Web.UI.HtmlControls.HtmlGenericControl

  '''<summary>
  '''txtEmail control.
  '''</summary>
  '''<remarks>
  '''Auto-generated field.
  '''To modify move field declaration from designer file to code-behind file.
  '''</remarks>
  Protected WithEvents txtEmail As Global.System.Web.UI.WebControls.TextBox

  '''<summary>
  '''valUsernameIsValidEmail control.
  '''</summary>
  '''<remarks>
  '''Auto-generated field.
  '''To modify move field declaration from designer file to code-behind file.
  '''</remarks>
  Protected WithEvents valUsernameIsValidEmail As Global.System.Web.UI.WebControls.RegularExpressionValidator

  '''<summary>
  '''valDuplicateEmail control.
  '''</summary>
  '''<remarks>
  '''Auto-generated field.
  '''To modify move field declaration from designer file to code-behind file.
  '''</remarks>
  Protected WithEvents valDuplicateEmail As Global.System.Web.UI.WebControls.CustomValidator

  '''<summary>
  '''valUsername control.
  '''</summary>
  '''<remarks>
  '''Auto-generated field.
  '''To modify move field declaration from designer file to code-behind file.
  '''</remarks>
  Protected WithEvents valUsername As Global.System.Web.UI.WebControls.RequiredFieldValidator

  '''<summary>
  '''txtSocialSecurity1 control.
  '''</summary>
  '''<remarks>
  '''Auto-generated field.
  '''To modify move field declaration from designer file to code-behind file.
  '''</remarks>
  Protected WithEvents txtSocialSecurity1 As Global.System.Web.UI.WebControls.TextBox

  '''<summary>
  '''txtSocialSecurity2 control.
  '''</summary>
  '''<remarks>
  '''Auto-generated field.
  '''To modify move field declaration from designer file to code-behind file.
  '''</remarks>
  Protected WithEvents txtSocialSecurity2 As Global.System.Web.UI.WebControls.TextBox

  '''<summary>
  '''txtSocialSecurity3 control.
  '''</summary>
  '''<remarks>
  '''Auto-generated field.
  '''To modify move field declaration from designer file to code-behind file.
  '''</remarks>
  Protected WithEvents txtSocialSecurity3 As Global.System.Web.UI.WebControls.TextBox

  '''<summary>
  '''FilteredTextBoxExtender13 control.
  '''</summary>
  '''<remarks>
  '''Auto-generated field.
  '''To modify move field declaration from designer file to code-behind file.
  '''</remarks>
  Protected WithEvents FilteredTextBoxExtender13 As Global.AjaxControlToolkit.FilteredTextBoxExtender

  '''<summary>
  '''FilteredTextBoxExtender14 control.
  '''</summary>
  '''<remarks>
  '''Auto-generated field.
  '''To modify move field declaration from designer file to code-behind file.
  '''</remarks>
  Protected WithEvents FilteredTextBoxExtender14 As Global.AjaxControlToolkit.FilteredTextBoxExtender

  '''<summary>
  '''FilteredTextBoxExtender15 control.
  '''</summary>
  '''<remarks>
  '''Auto-generated field.
  '''To modify move field declaration from designer file to code-behind file.
  '''</remarks>
  Protected WithEvents FilteredTextBoxExtender15 As Global.AjaxControlToolkit.FilteredTextBoxExtender

  '''<summary>
  '''valSocialSecurity control.
  '''</summary>
  '''<remarks>
  '''Auto-generated field.
  '''To modify move field declaration from designer file to code-behind file.
  '''</remarks>
  Protected WithEvents valSocialSecurity As Global.System.Web.UI.WebControls.CustomValidator

  '''<summary>
  '''txtFirstName control.
  '''</summary>
  '''<remarks>
  '''Auto-generated field.
  '''To modify move field declaration from designer file to code-behind file.
  '''</remarks>
  Protected WithEvents txtFirstName As Global.System.Web.UI.WebControls.TextBox

  '''<summary>
  '''valFirstName control.
  '''</summary>
  '''<remarks>
  '''Auto-generated field.
  '''To modify move field declaration from designer file to code-behind file.
  '''</remarks>
  Protected WithEvents valFirstName As Global.System.Web.UI.WebControls.RequiredFieldValidator

  '''<summary>
  '''txtMiddleName control.
  '''</summary>
  '''<remarks>
  '''Auto-generated field.
  '''To modify move field declaration from designer file to code-behind file.
  '''</remarks>
  Protected WithEvents txtMiddleName As Global.System.Web.UI.WebControls.TextBox

  '''<summary>
  '''valMiddleName control.
  '''</summary>
  '''<remarks>
  '''Auto-generated field.
  '''To modify move field declaration from designer file to code-behind file.
  '''</remarks>
  Protected WithEvents valMiddleName As Global.System.Web.UI.WebControls.RequiredFieldValidator

  '''<summary>
  '''txtLastName control.
  '''</summary>
  '''<remarks>
  '''Auto-generated field.
  '''To modify move field declaration from designer file to code-behind file.
  '''</remarks>
  Protected WithEvents txtLastName As Global.System.Web.UI.WebControls.TextBox

  '''<summary>
  '''valLastName control.
  '''</summary>
  '''<remarks>
  '''Auto-generated field.
  '''To modify move field declaration from designer file to code-behind file.
  '''</remarks>
  Protected WithEvents valLastName As Global.System.Web.UI.WebControls.RequiredFieldValidator

  '''<summary>
  '''txtDOB control.
  '''</summary>
  '''<remarks>
  '''Auto-generated field.
  '''To modify move field declaration from designer file to code-behind file.
  '''</remarks>
  Protected WithEvents txtDOB As Global.System.Web.UI.WebControls.TextBox

  '''<summary>
  '''lnkCalendarDOB control.
  '''</summary>
  '''<remarks>
  '''Auto-generated field.
  '''To modify move field declaration from designer file to code-behind file.
  '''</remarks>
  Protected WithEvents lnkCalendarDOB As Global.System.Web.UI.HtmlControls.HtmlAnchor

  '''<summary>
  '''valDOB control.
  '''</summary>
  '''<remarks>
  '''Auto-generated field.
  '''To modify move field declaration from designer file to code-behind file.
  '''</remarks>
  Protected WithEvents valDOB As Global.System.Web.UI.WebControls.RequiredFieldValidator

  '''<summary>
  '''calDOB control.
  '''</summary>
  '''<remarks>
  '''Auto-generated field.
  '''To modify move field declaration from designer file to code-behind file.
  '''</remarks>
  Protected WithEvents calDOB As Global.AjaxControlToolkit.CalendarExtender

  '''<summary>
  '''txtPhone1 control.
  '''</summary>
  '''<remarks>
  '''Auto-generated field.
  '''To modify move field declaration from designer file to code-behind file.
  '''</remarks>
  Protected WithEvents txtPhone1 As Global.System.Web.UI.WebControls.TextBox

  '''<summary>
  '''txtPhone2 control.
  '''</summary>
  '''<remarks>
  '''Auto-generated field.
  '''To modify move field declaration from designer file to code-behind file.
  '''</remarks>
  Protected WithEvents txtPhone2 As Global.System.Web.UI.WebControls.TextBox

  '''<summary>
  '''txtPhone3 control.
  '''</summary>
  '''<remarks>
  '''Auto-generated field.
  '''To modify move field declaration from designer file to code-behind file.
  '''</remarks>
  Protected WithEvents txtPhone3 As Global.System.Web.UI.WebControls.TextBox

  '''<summary>
  '''FilteredTextBoxExtender1 control.
  '''</summary>
  '''<remarks>
  '''Auto-generated field.
  '''To modify move field declaration from designer file to code-behind file.
  '''</remarks>
  Protected WithEvents FilteredTextBoxExtender1 As Global.AjaxControlToolkit.FilteredTextBoxExtender

  '''<summary>
  '''FilteredTextBoxExtender2 control.
  '''</summary>
  '''<remarks>
  '''Auto-generated field.
  '''To modify move field declaration from designer file to code-behind file.
  '''</remarks>
  Protected WithEvents FilteredTextBoxExtender2 As Global.AjaxControlToolkit.FilteredTextBoxExtender

  '''<summary>
  '''FilteredTextBoxExtender3 control.
  '''</summary>
  '''<remarks>
  '''Auto-generated field.
  '''To modify move field declaration from designer file to code-behind file.
  '''</remarks>
  Protected WithEvents FilteredTextBoxExtender3 As Global.AjaxControlToolkit.FilteredTextBoxExtender

  '''<summary>
  '''valPhone control.
  '''</summary>
  '''<remarks>
  '''Auto-generated field.
  '''To modify move field declaration from designer file to code-behind file.
  '''</remarks>
  Protected WithEvents valPhone As Global.System.Web.UI.WebControls.CustomValidator

  '''<summary>
  '''chkGender control.
  '''</summary>
  '''<remarks>
  '''Auto-generated field.
  '''To modify move field declaration from designer file to code-behind file.
  '''</remarks>
  Protected WithEvents chkGender As Global.System.Web.UI.WebControls.RadioButtonList

  '''<summary>
  '''valGender control.
  '''</summary>
  '''<remarks>
  '''Auto-generated field.
  '''To modify move field declaration from designer file to code-behind file.
  '''</remarks>
  Protected WithEvents valGender As Global.System.Web.UI.WebControls.RequiredFieldValidator

  '''<summary>
  '''drpMaritalStatus control.
  '''</summary>
  '''<remarks>
  '''Auto-generated field.
  '''To modify move field declaration from designer file to code-behind file.
  '''</remarks>
  Protected WithEvents drpMaritalStatus As Global.System.Web.UI.WebControls.DropDownList

  '''<summary>
  '''valMaritalStatus control.
  '''</summary>
  '''<remarks>
  '''Auto-generated field.
  '''To modify move field declaration from designer file to code-behind file.
  '''</remarks>
  Protected WithEvents valMaritalStatus As Global.System.Web.UI.WebControls.RequiredFieldValidator

  '''<summary>
  '''txtStreet control.
  '''</summary>
  '''<remarks>
  '''Auto-generated field.
  '''To modify move field declaration from designer file to code-behind file.
  '''</remarks>
  Protected WithEvents txtStreet As Global.System.Web.UI.WebControls.TextBox

  '''<summary>
  '''valStreet control.
  '''</summary>
  '''<remarks>
  '''Auto-generated field.
  '''To modify move field declaration from designer file to code-behind file.
  '''</remarks>
  Protected WithEvents valStreet As Global.System.Web.UI.WebControls.RequiredFieldValidator

  '''<summary>
  '''txtCity control.
  '''</summary>
  '''<remarks>
  '''Auto-generated field.
  '''To modify move field declaration from designer file to code-behind file.
  '''</remarks>
  Protected WithEvents txtCity As Global.System.Web.UI.WebControls.TextBox

  '''<summary>
  '''valCity control.
  '''</summary>
  '''<remarks>
  '''Auto-generated field.
  '''To modify move field declaration from designer file to code-behind file.
  '''</remarks>
  Protected WithEvents valCity As Global.System.Web.UI.WebControls.RequiredFieldValidator

  '''<summary>
  '''drpState control.
  '''</summary>
  '''<remarks>
  '''Auto-generated field.
  '''To modify move field declaration from designer file to code-behind file.
  '''</remarks>
  Protected WithEvents drpState As Global.System.Web.UI.WebControls.DropDownList

  '''<summary>
  '''valState control.
  '''</summary>
  '''<remarks>
  '''Auto-generated field.
  '''To modify move field declaration from designer file to code-behind file.
  '''</remarks>
  Protected WithEvents valState As Global.System.Web.UI.WebControls.RequiredFieldValidator

  '''<summary>
  '''txtZip control.
  '''</summary>
  '''<remarks>
  '''Auto-generated field.
  '''To modify move field declaration from designer file to code-behind file.
  '''</remarks>
  Protected WithEvents txtZip As Global.System.Web.UI.WebControls.TextBox

  '''<summary>
  '''valZip control.
  '''</summary>
  '''<remarks>
  '''Auto-generated field.
  '''To modify move field declaration from designer file to code-behind file.
  '''</remarks>
  Protected WithEvents valZip As Global.System.Web.UI.WebControls.RequiredFieldValidator

  '''<summary>
  '''txtBeganLiving control.
  '''</summary>
  '''<remarks>
  '''Auto-generated field.
  '''To modify move field declaration from designer file to code-behind file.
  '''</remarks>
  Protected WithEvents txtBeganLiving As Global.System.Web.UI.WebControls.TextBox

  '''<summary>
  '''lnkCalendarBeganLiving control.
  '''</summary>
  '''<remarks>
  '''Auto-generated field.
  '''To modify move field declaration from designer file to code-behind file.
  '''</remarks>
  Protected WithEvents lnkCalendarBeganLiving As Global.System.Web.UI.HtmlControls.HtmlAnchor

  '''<summary>
  '''valBeganLiving control.
  '''</summary>
  '''<remarks>
  '''Auto-generated field.
  '''To modify move field declaration from designer file to code-behind file.
  '''</remarks>
  Protected WithEvents valBeganLiving As Global.System.Web.UI.WebControls.RequiredFieldValidator

  '''<summary>
  '''calBeganLiving control.
  '''</summary>
  '''<remarks>
  '''Auto-generated field.
  '''To modify move field declaration from designer file to code-behind file.
  '''</remarks>
  Protected WithEvents calBeganLiving As Global.AjaxControlToolkit.CalendarExtender

  '''<summary>
  '''drpHomeType control.
  '''</summary>
  '''<remarks>
  '''Auto-generated field.
  '''To modify move field declaration from designer file to code-behind file.
  '''</remarks>
  Protected WithEvents drpHomeType As Global.System.Web.UI.WebControls.DropDownList

  '''<summary>
  '''valDrpHomeType control.
  '''</summary>
  '''<remarks>
  '''Auto-generated field.
  '''To modify move field declaration from designer file to code-behind file.
  '''</remarks>
  Protected WithEvents valDrpHomeType As Global.System.Web.UI.WebControls.RequiredFieldValidator

  '''<summary>
  '''litHomeType control.
  '''</summary>
  '''<remarks>
  '''Auto-generated field.
  '''To modify move field declaration from designer file to code-behind file.
  '''</remarks>
  Protected WithEvents litHomeType As Global.System.Web.UI.WebControls.Literal

  '''<summary>
  '''txtHomeType control.
  '''</summary>
  '''<remarks>
  '''Auto-generated field.
  '''To modify move field declaration from designer file to code-behind file.
  '''</remarks>
  Protected WithEvents txtHomeType As Global.System.Web.UI.WebControls.TextBox

  '''<summary>
  '''valTxtHomeType control.
  '''</summary>
  '''<remarks>
  '''Auto-generated field.
  '''To modify move field declaration from designer file to code-behind file.
  '''</remarks>
  Protected WithEvents valTxtHomeType As Global.System.Web.UI.WebControls.RequiredFieldValidator

  '''<summary>
  '''drpNationality control.
  '''</summary>
  '''<remarks>
  '''Auto-generated field.
  '''To modify move field declaration from designer file to code-behind file.
  '''</remarks>
  Protected WithEvents drpNationality As Global.System.Web.UI.WebControls.DropDownList

  '''<summary>
  '''valNationality control.
  '''</summary>
  '''<remarks>
  '''Auto-generated field.
  '''To modify move field declaration from designer file to code-behind file.
  '''</remarks>
  Protected WithEvents valNationality As Global.System.Web.UI.WebControls.RequiredFieldValidator

  '''<summary>
  '''drpCitizenship control.
  '''</summary>
  '''<remarks>
  '''Auto-generated field.
  '''To modify move field declaration from designer file to code-behind file.
  '''</remarks>
  Protected WithEvents drpCitizenship As Global.System.Web.UI.WebControls.DropDownList

  '''<summary>
  '''valCitizenship control.
  '''</summary>
  '''<remarks>
  '''Auto-generated field.
  '''To modify move field declaration from designer file to code-behind file.
  '''</remarks>
  Protected WithEvents valCitizenship As Global.System.Web.UI.WebControls.RequiredFieldValidator

  '''<summary>
  '''txtMasjidName control.
  '''</summary>
  '''<remarks>
  '''Auto-generated field.
  '''To modify move field declaration from designer file to code-behind file.
  '''</remarks>
  Protected WithEvents txtMasjidName As Global.System.Web.UI.WebControls.TextBox

  '''<summary>
  '''valMasjidName control.
  '''</summary>
  '''<remarks>
  '''Auto-generated field.
  '''To modify move field declaration from designer file to code-behind file.
  '''</remarks>
  Protected WithEvents valMasjidName As Global.System.Web.UI.WebControls.RequiredFieldValidator

  '''<summary>
  '''txtMasjidPhone1 control.
  '''</summary>
  '''<remarks>
  '''Auto-generated field.
  '''To modify move field declaration from designer file to code-behind file.
  '''</remarks>
  Protected WithEvents txtMasjidPhone1 As Global.System.Web.UI.WebControls.TextBox

  '''<summary>
  '''txtMasjidPhone2 control.
  '''</summary>
  '''<remarks>
  '''Auto-generated field.
  '''To modify move field declaration from designer file to code-behind file.
  '''</remarks>
  Protected WithEvents txtMasjidPhone2 As Global.System.Web.UI.WebControls.TextBox

  '''<summary>
  '''txtMasjidPhone3 control.
  '''</summary>
  '''<remarks>
  '''Auto-generated field.
  '''To modify move field declaration from designer file to code-behind file.
  '''</remarks>
  Protected WithEvents txtMasjidPhone3 As Global.System.Web.UI.WebControls.TextBox

  '''<summary>
  '''FilteredTextBoxExtender4 control.
  '''</summary>
  '''<remarks>
  '''Auto-generated field.
  '''To modify move field declaration from designer file to code-behind file.
  '''</remarks>
  Protected WithEvents FilteredTextBoxExtender4 As Global.AjaxControlToolkit.FilteredTextBoxExtender

  '''<summary>
  '''FilteredTextBoxExtender5 control.
  '''</summary>
  '''<remarks>
  '''Auto-generated field.
  '''To modify move field declaration from designer file to code-behind file.
  '''</remarks>
  Protected WithEvents FilteredTextBoxExtender5 As Global.AjaxControlToolkit.FilteredTextBoxExtender

  '''<summary>
  '''FilteredTextBoxExtender6 control.
  '''</summary>
  '''<remarks>
  '''Auto-generated field.
  '''To modify move field declaration from designer file to code-behind file.
  '''</remarks>
  Protected WithEvents FilteredTextBoxExtender6 As Global.AjaxControlToolkit.FilteredTextBoxExtender

  '''<summary>
  '''valMasjidPhone control.
  '''</summary>
  '''<remarks>
  '''Auto-generated field.
  '''To modify move field declaration from designer file to code-behind file.
  '''</remarks>
  Protected WithEvents valMasjidPhone As Global.System.Web.UI.WebControls.CustomValidator

  '''<summary>
  '''lstLanguages control.
  '''</summary>
  '''<remarks>
  '''Auto-generated field.
  '''To modify move field declaration from designer file to code-behind file.
  '''</remarks>
  Protected WithEvents lstLanguages As Global.System.Web.UI.WebControls.ListBox

  '''<summary>
  '''btnAddLanguage control.
  '''</summary>
  '''<remarks>
  '''Auto-generated field.
  '''To modify move field declaration from designer file to code-behind file.
  '''</remarks>
  Protected WithEvents btnAddLanguage As Global.System.Web.UI.WebControls.LinkButton

  '''<summary>
  '''btnDeleteLanguage control.
  '''</summary>
  '''<remarks>
  '''Auto-generated field.
  '''To modify move field declaration from designer file to code-behind file.
  '''</remarks>
  Protected WithEvents btnDeleteLanguage As Global.System.Web.UI.WebControls.LinkButton

  '''<summary>
  '''lstSpoken control.
  '''</summary>
  '''<remarks>
  '''Auto-generated field.
  '''To modify move field declaration from designer file to code-behind file.
  '''</remarks>
  Protected WithEvents lstSpoken As Global.System.Web.UI.WebControls.ListBox

  '''<summary>
  '''txtSkillCertification control.
  '''</summary>
  '''<remarks>
  '''Auto-generated field.
  '''To modify move field declaration from designer file to code-behind file.
  '''</remarks>
  Protected WithEvents txtSkillCertification As Global.System.Web.UI.WebControls.TextBox

  '''<summary>
  '''btnAddCertification control.
  '''</summary>
  '''<remarks>
  '''Auto-generated field.
  '''To modify move field declaration from designer file to code-behind file.
  '''</remarks>
  Protected WithEvents btnAddCertification As Global.System.Web.UI.WebControls.LinkButton

  '''<summary>
  '''lstSkillCertification control.
  '''</summary>
  '''<remarks>
  '''Auto-generated field.
  '''To modify move field declaration from designer file to code-behind file.
  '''</remarks>
  Protected WithEvents lstSkillCertification As Global.System.Web.UI.WebControls.ListBox

  '''<summary>
  '''btnRemoveCertification control.
  '''</summary>
  '''<remarks>
  '''Auto-generated field.
  '''To modify move field declaration from designer file to code-behind file.
  '''</remarks>
  Protected WithEvents btnRemoveCertification As Global.System.Web.UI.WebControls.LinkButton

  '''<summary>
  '''drpHighestEducation control.
  '''</summary>
  '''<remarks>
  '''Auto-generated field.
  '''To modify move field declaration from designer file to code-behind file.
  '''</remarks>
  Protected WithEvents drpHighestEducation As Global.System.Web.UI.WebControls.DropDownList

  '''<summary>
  '''valHighestEducation control.
  '''</summary>
  '''<remarks>
  '''Auto-generated field.
  '''To modify move field declaration from designer file to code-behind file.
  '''</remarks>
  Protected WithEvents valHighestEducation As Global.System.Web.UI.WebControls.RequiredFieldValidator

  '''<summary>
  '''chkIsInternational control.
  '''</summary>
  '''<remarks>
  '''Auto-generated field.
  '''To modify move field declaration from designer file to code-behind file.
  '''</remarks>
  Protected WithEvents chkIsInternational As Global.System.Web.UI.WebControls.CheckBox

  '''<summary>
  '''CustomValidator3 control.
  '''</summary>
  '''<remarks>
  '''Auto-generated field.
  '''To modify move field declaration from designer file to code-behind file.
  '''</remarks>
  Protected WithEvents CustomValidator3 As Global.System.Web.UI.WebControls.CustomValidator

  '''<summary>
  '''txtSchoolName control.
  '''</summary>
  '''<remarks>
  '''Auto-generated field.
  '''To modify move field declaration from designer file to code-behind file.
  '''</remarks>
  Protected WithEvents txtSchoolName As Global.System.Web.UI.WebControls.TextBox

  '''<summary>
  '''valSchoolName control.
  '''</summary>
  '''<remarks>
  '''Auto-generated field.
  '''To modify move field declaration from designer file to code-behind file.
  '''</remarks>
  Protected WithEvents valSchoolName As Global.System.Web.UI.WebControls.RequiredFieldValidator

  '''<summary>
  '''txtSchoolCity control.
  '''</summary>
  '''<remarks>
  '''Auto-generated field.
  '''To modify move field declaration from designer file to code-behind file.
  '''</remarks>
  Protected WithEvents txtSchoolCity As Global.System.Web.UI.WebControls.TextBox

  '''<summary>
  '''valSchoolCity control.
  '''</summary>
  '''<remarks>
  '''Auto-generated field.
  '''To modify move field declaration from designer file to code-behind file.
  '''</remarks>
  Protected WithEvents valSchoolCity As Global.System.Web.UI.WebControls.RequiredFieldValidator

  '''<summary>
  '''pnlDomestic control.
  '''</summary>
  '''<remarks>
  '''Auto-generated field.
  '''To modify move field declaration from designer file to code-behind file.
  '''</remarks>
  Protected WithEvents pnlDomestic As Global.System.Web.UI.WebControls.Panel

  '''<summary>
  '''txtSchoolStreet control.
  '''</summary>
  '''<remarks>
  '''Auto-generated field.
  '''To modify move field declaration from designer file to code-behind file.
  '''</remarks>
  Protected WithEvents txtSchoolStreet As Global.System.Web.UI.WebControls.TextBox

  '''<summary>
  '''valSchoolStreet control.
  '''</summary>
  '''<remarks>
  '''Auto-generated field.
  '''To modify move field declaration from designer file to code-behind file.
  '''</remarks>
  Protected WithEvents valSchoolStreet As Global.System.Web.UI.WebControls.RequiredFieldValidator

  '''<summary>
  '''drpSchoolState control.
  '''</summary>
  '''<remarks>
  '''Auto-generated field.
  '''To modify move field declaration from designer file to code-behind file.
  '''</remarks>
  Protected WithEvents drpSchoolState As Global.System.Web.UI.WebControls.DropDownList

  '''<summary>
  '''valSchoolState control.
  '''</summary>
  '''<remarks>
  '''Auto-generated field.
  '''To modify move field declaration from designer file to code-behind file.
  '''</remarks>
  Protected WithEvents valSchoolState As Global.System.Web.UI.WebControls.RequiredFieldValidator

  '''<summary>
  '''txtSchoolZip control.
  '''</summary>
  '''<remarks>
  '''Auto-generated field.
  '''To modify move field declaration from designer file to code-behind file.
  '''</remarks>
  Protected WithEvents txtSchoolZip As Global.System.Web.UI.WebControls.TextBox

  '''<summary>
  '''valSchoolZip control.
  '''</summary>
  '''<remarks>
  '''Auto-generated field.
  '''To modify move field declaration from designer file to code-behind file.
  '''</remarks>
  Protected WithEvents valSchoolZip As Global.System.Web.UI.WebControls.RequiredFieldValidator

  '''<summary>
  '''pnlInternational control.
  '''</summary>
  '''<remarks>
  '''Auto-generated field.
  '''To modify move field declaration from designer file to code-behind file.
  '''</remarks>
  Protected WithEvents pnlInternational As Global.System.Web.UI.WebControls.Panel

  '''<summary>
  '''drpSchoolCountry control.
  '''</summary>
  '''<remarks>
  '''Auto-generated field.
  '''To modify move field declaration from designer file to code-behind file.
  '''</remarks>
  Protected WithEvents drpSchoolCountry As Global.System.Web.UI.WebControls.DropDownList

  '''<summary>
  '''valSchoolCountry control.
  '''</summary>
  '''<remarks>
  '''Auto-generated field.
  '''To modify move field declaration from designer file to code-behind file.
  '''</remarks>
  Protected WithEvents valSchoolCountry As Global.System.Web.UI.WebControls.RequiredFieldValidator

  '''<summary>
  '''pnlHusbandInformation control.
  '''</summary>
  '''<remarks>
  '''Auto-generated field.
  '''To modify move field declaration from designer file to code-behind file.
  '''</remarks>
  Protected WithEvents pnlHusbandInformation As Global.System.Web.UI.WebControls.Panel

  '''<summary>
  '''txtHusbandFirstName control.
  '''</summary>
  '''<remarks>
  '''Auto-generated field.
  '''To modify move field declaration from designer file to code-behind file.
  '''</remarks>
  Protected WithEvents txtHusbandFirstName As Global.System.Web.UI.WebControls.TextBox

  '''<summary>
  '''valHusbandFirstName control.
  '''</summary>
  '''<remarks>
  '''Auto-generated field.
  '''To modify move field declaration from designer file to code-behind file.
  '''</remarks>
  Protected WithEvents valHusbandFirstName As Global.System.Web.UI.WebControls.RequiredFieldValidator

  '''<summary>
  '''txtHusbandMiddleName control.
  '''</summary>
  '''<remarks>
  '''Auto-generated field.
  '''To modify move field declaration from designer file to code-behind file.
  '''</remarks>
  Protected WithEvents txtHusbandMiddleName As Global.System.Web.UI.WebControls.TextBox

  '''<summary>
  '''valHusbandMiddleName control.
  '''</summary>
  '''<remarks>
  '''Auto-generated field.
  '''To modify move field declaration from designer file to code-behind file.
  '''</remarks>
  Protected WithEvents valHusbandMiddleName As Global.System.Web.UI.WebControls.CustomValidator

  '''<summary>
  '''txtHusbandLastName control.
  '''</summary>
  '''<remarks>
  '''Auto-generated field.
  '''To modify move field declaration from designer file to code-behind file.
  '''</remarks>
  Protected WithEvents txtHusbandLastName As Global.System.Web.UI.WebControls.TextBox

  '''<summary>
  '''valHusbandLastName control.
  '''</summary>
  '''<remarks>
  '''Auto-generated field.
  '''To modify move field declaration from designer file to code-behind file.
  '''</remarks>
  Protected WithEvents valHusbandLastName As Global.System.Web.UI.WebControls.RequiredFieldValidator

  '''<summary>
  '''txtHusbandPhone control.
  '''</summary>
  '''<remarks>
  '''Auto-generated field.
  '''To modify move field declaration from designer file to code-behind file.
  '''</remarks>
  Protected WithEvents txtHusbandPhone As Global.System.Web.UI.WebControls.TextBox

  '''<summary>
  '''valHusbandPhone control.
  '''</summary>
  '''<remarks>
  '''Auto-generated field.
  '''To modify move field declaration from designer file to code-behind file.
  '''</remarks>
  Protected WithEvents valHusbandPhone As Global.System.Web.UI.WebControls.RequiredFieldValidator

  '''<summary>
  '''txtHusbandEmail control.
  '''</summary>
  '''<remarks>
  '''Auto-generated field.
  '''To modify move field declaration from designer file to code-behind file.
  '''</remarks>
  Protected WithEvents txtHusbandEmail As Global.System.Web.UI.WebControls.TextBox

  '''<summary>
  '''RegularExpressionValidator13 control.
  '''</summary>
  '''<remarks>
  '''Auto-generated field.
  '''To modify move field declaration from designer file to code-behind file.
  '''</remarks>
  Protected WithEvents RegularExpressionValidator13 As Global.System.Web.UI.WebControls.RegularExpressionValidator

  '''<summary>
  '''valHusbandEmail control.
  '''</summary>
  '''<remarks>
  '''Auto-generated field.
  '''To modify move field declaration from designer file to code-behind file.
  '''</remarks>
  Protected WithEvents valHusbandEmail As Global.System.Web.UI.WebControls.RequiredFieldValidator

  '''<summary>
  '''chkHusbandApplied control.
  '''</summary>
  '''<remarks>
  '''Auto-generated field.
  '''To modify move field declaration from designer file to code-behind file.
  '''</remarks>
  Protected WithEvents chkHusbandApplied As Global.System.Web.UI.WebControls.RadioButtonList

  '''<summary>
  '''valHusbandApplied control.
  '''</summary>
  '''<remarks>
  '''Auto-generated field.
  '''To modify move field declaration from designer file to code-behind file.
  '''</remarks>
  Protected WithEvents valHusbandApplied As Global.System.Web.UI.WebControls.RequiredFieldValidator

  '''<summary>
  '''txtHusbandExplanation control.
  '''</summary>
  '''<remarks>
  '''Auto-generated field.
  '''To modify move field declaration from designer file to code-behind file.
  '''</remarks>
  Protected WithEvents txtHusbandExplanation As Global.System.Web.UI.WebControls.TextBox

  '''<summary>
  '''valHusbandExplanation control.
  '''</summary>
  '''<remarks>
  '''Auto-generated field.
  '''To modify move field declaration from designer file to code-behind file.
  '''</remarks>
  Protected WithEvents valHusbandExplanation As Global.System.Web.UI.WebControls.RequiredFieldValidator

  '''<summary>
  '''pnlPassword control.
  '''</summary>
  '''<remarks>
  '''Auto-generated field.
  '''To modify move field declaration from designer file to code-behind file.
  '''</remarks>
  Protected WithEvents pnlPassword As Global.System.Web.UI.WebControls.Panel

  '''<summary>
  '''txtPassword control.
  '''</summary>
  '''<remarks>
  '''Auto-generated field.
  '''To modify move field declaration from designer file to code-behind file.
  '''</remarks>
  Protected WithEvents txtPassword As Global.System.Web.UI.WebControls.TextBox

  '''<summary>
  '''valPassword control.
  '''</summary>
  '''<remarks>
  '''Auto-generated field.
  '''To modify move field declaration from designer file to code-behind file.
  '''</remarks>
  Protected WithEvents valPassword As Global.System.Web.UI.WebControls.RequiredFieldValidator

  '''<summary>
  '''valUserRequiredSave control.
  '''</summary>
  '''<remarks>
  '''Auto-generated field.
  '''To modify move field declaration from designer file to code-behind file.
  '''</remarks>
  Protected WithEvents valUserRequiredSave As Global.System.Web.UI.WebControls.CustomValidator

  '''<summary>
  '''lblSaved control.
  '''</summary>
  '''<remarks>
  '''Auto-generated field.
  '''To modify move field declaration from designer file to code-behind file.
  '''</remarks>
  Protected WithEvents lblSaved As Global.System.Web.UI.WebControls.Label

  '''<summary>
  '''btnSave control.
  '''</summary>
  '''<remarks>
  '''Auto-generated field.
  '''To modify move field declaration from designer file to code-behind file.
  '''</remarks>
  Protected WithEvents btnSave As Global.System.Web.UI.WebControls.Button
End Class
