'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated from a template.
'
'     Manual changes to this file may cause unexpected behavior in your application.
'     Manual changes to this file will be overwritten if the code is regenerated.
' </auto-generated>
'------------------------------------------------------------------------------

Imports System
Imports System.Collections.Generic

Partial Public Class REFERENCE
    Public Property referenceId As Integer
    Public Property userId As Nullable(Of Integer)
    Public Property firstName As String
    Public Property middleName As String
    Public Property lastName As String
    Public Property referenceEmail As String
    Public Property referencePhone As String
    Public Property referenceKnownSince As Nullable(Of Date)
    Public Property referenceRelationship As String
    Public Property referenceStreet As String
    Public Property referenceCity As String
    Public Property referenceStateAbbr As String
    Public Property referenceZip As String

    Public Overridable Property USER As USER

End Class
