'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated from a template.
'
'     Manual changes to this file may cause unexpected behavior in your application.
'     Manual changes to this file will be overwritten if the code is regenerated.
' </auto-generated>
'------------------------------------------------------------------------------

Imports System
Imports System.Collections.Generic

Partial Public Class REFERENCE
    Public Property referenceId As Integer
    Public Property userId As Nullable(Of Integer)
    Public Property firstName As String
    Public Property middleName As String
    Public Property lastName As String
    Public Property phone As String
    Public Property knownSince As Nullable(Of Date)
    Public Property relationship As String
    Public Property street As String
    Public Property city As String
    Public Property stateAbbr As String
    Public Property zip As String

    Public Overridable Property STATE As STATE
    Public Overridable Property USER As USER

End Class
