'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated by a tool.
'
'     Changes to this file may cause incorrect behavior and will be lost if
'     the code is regenerated. 
' </auto-generated>
'------------------------------------------------------------------------------

Option Strict On
Option Explicit On


Partial Public Class Site_Mobile

  '''<summary>
  '''pnlAnonymous control.
  '''</summary>
  '''<remarks>
  '''Auto-generated field.
  '''To modify move field declaration from designer file to code-behind file.
  '''</remarks>
  Protected WithEvents pnlAnonymous As Global.System.Web.UI.WebControls.Panel

  '''<summary>
  '''drpTranslation control.
  '''</summary>
  '''<remarks>
  '''Auto-generated field.
  '''To modify move field declaration from designer file to code-behind file.
  '''</remarks>
  Protected WithEvents drpTranslation As Global.System.Web.UI.WebControls.DropDownList

  '''<summary>
  '''UpdatePanel1 control.
  '''</summary>
  '''<remarks>
  '''Auto-generated field.
  '''To modify move field declaration from designer file to code-behind file.
  '''</remarks>
  Protected WithEvents UpdatePanel1 As Global.System.Web.UI.UpdatePanel

  '''<summary>
  '''txtSearch control.
  '''</summary>
  '''<remarks>
  '''Auto-generated field.
  '''To modify move field declaration from designer file to code-behind file.
  '''</remarks>
  Protected WithEvents txtSearch As Global.System.Web.UI.WebControls.TextBox

  '''<summary>
  '''ajaxTxtSearch control.
  '''</summary>
  '''<remarks>
  '''Auto-generated field.
  '''To modify move field declaration from designer file to code-behind file.
  '''</remarks>
  Protected WithEvents ajaxTxtSearch As Global.AjaxControlToolkit.PopupControlExtender

  '''<summary>
  '''pnlSearchResults control.
  '''</summary>
  '''<remarks>
  '''Auto-generated field.
  '''To modify move field declaration from designer file to code-behind file.
  '''</remarks>
  Protected WithEvents pnlSearchResults As Global.System.Web.UI.WebControls.Panel

  '''<summary>
  '''rptSearchResults control.
  '''</summary>
  '''<remarks>
  '''Auto-generated field.
  '''To modify move field declaration from designer file to code-behind file.
  '''</remarks>
  Protected WithEvents rptSearchResults As Global.System.Web.UI.WebControls.Repeater

  '''<summary>
  '''pnlApplicant control.
  '''</summary>
  '''<remarks>
  '''Auto-generated field.
  '''To modify move field declaration from designer file to code-behind file.
  '''</remarks>
  Protected WithEvents pnlApplicant As Global.System.Web.UI.WebControls.Panel

  '''<summary>
  '''A11 control.
  '''</summary>
  '''<remarks>
  '''Auto-generated field.
  '''To modify move field declaration from designer file to code-behind file.
  '''</remarks>
  Protected WithEvents A11 As Global.System.Web.UI.HtmlControls.HtmlAnchor

  '''<summary>
  '''lnkApplication control.
  '''</summary>
  '''<remarks>
  '''Auto-generated field.
  '''To modify move field declaration from designer file to code-behind file.
  '''</remarks>
  Protected WithEvents lnkApplication As Global.System.Web.UI.HtmlControls.HtmlAnchor

  '''<summary>
  '''A1 control.
  '''</summary>
  '''<remarks>
  '''Auto-generated field.
  '''To modify move field declaration from designer file to code-behind file.
  '''</remarks>
  Protected WithEvents A1 As Global.System.Web.UI.HtmlControls.HtmlAnchor

  '''<summary>
  '''A7 control.
  '''</summary>
  '''<remarks>
  '''Auto-generated field.
  '''To modify move field declaration from designer file to code-behind file.
  '''</remarks>
  Protected WithEvents A7 As Global.System.Web.UI.HtmlControls.HtmlAnchor

  '''<summary>
  '''lblNameApplicant control.
  '''</summary>
  '''<remarks>
  '''Auto-generated field.
  '''To modify move field declaration from designer file to code-behind file.
  '''</remarks>
  Protected WithEvents lblNameApplicant As Global.System.Web.UI.WebControls.Label

  '''<summary>
  '''pnlAdministrator control.
  '''</summary>
  '''<remarks>
  '''Auto-generated field.
  '''To modify move field declaration from designer file to code-behind file.
  '''</remarks>
  Protected WithEvents pnlAdministrator As Global.System.Web.UI.WebControls.Panel

  '''<summary>
  '''A13 control.
  '''</summary>
  '''<remarks>
  '''Auto-generated field.
  '''To modify move field declaration from designer file to code-behind file.
  '''</remarks>
  Protected WithEvents A13 As Global.System.Web.UI.HtmlControls.HtmlAnchor

  '''<summary>
  '''A12 control.
  '''</summary>
  '''<remarks>
  '''Auto-generated field.
  '''To modify move field declaration from designer file to code-behind file.
  '''</remarks>
  Protected WithEvents A12 As Global.System.Web.UI.HtmlControls.HtmlAnchor

  '''<summary>
  '''A6 control.
  '''</summary>
  '''<remarks>
  '''Auto-generated field.
  '''To modify move field declaration from designer file to code-behind file.
  '''</remarks>
  Protected WithEvents A6 As Global.System.Web.UI.HtmlControls.HtmlAnchor

  '''<summary>
  '''lblNameAdministrator control.
  '''</summary>
  '''<remarks>
  '''Auto-generated field.
  '''To modify move field declaration from designer file to code-behind file.
  '''</remarks>
  Protected WithEvents lblNameAdministrator As Global.System.Web.UI.WebControls.Label

  '''<summary>
  '''pnlApprover control.
  '''</summary>
  '''<remarks>
  '''Auto-generated field.
  '''To modify move field declaration from designer file to code-behind file.
  '''</remarks>
  Protected WithEvents pnlApprover As Global.System.Web.UI.WebControls.Panel

  '''<summary>
  '''A4 control.
  '''</summary>
  '''<remarks>
  '''Auto-generated field.
  '''To modify move field declaration from designer file to code-behind file.
  '''</remarks>
  Protected WithEvents A4 As Global.System.Web.UI.HtmlControls.HtmlAnchor

  '''<summary>
  '''A5 control.
  '''</summary>
  '''<remarks>
  '''Auto-generated field.
  '''To modify move field declaration from designer file to code-behind file.
  '''</remarks>
  Protected WithEvents A5 As Global.System.Web.UI.HtmlControls.HtmlAnchor

  '''<summary>
  '''A2 control.
  '''</summary>
  '''<remarks>
  '''Auto-generated field.
  '''To modify move field declaration from designer file to code-behind file.
  '''</remarks>
  Protected WithEvents A2 As Global.System.Web.UI.HtmlControls.HtmlAnchor

  '''<summary>
  '''lblNameApprover control.
  '''</summary>
  '''<remarks>
  '''Auto-generated field.
  '''To modify move field declaration from designer file to code-behind file.
  '''</remarks>
  Protected WithEvents lblNameApprover As Global.System.Web.UI.WebControls.Label

  '''<summary>
  '''pnlFinancier control.
  '''</summary>
  '''<remarks>
  '''Auto-generated field.
  '''To modify move field declaration from designer file to code-behind file.
  '''</remarks>
  Protected WithEvents pnlFinancier As Global.System.Web.UI.WebControls.Panel

  '''<summary>
  '''A8 control.
  '''</summary>
  '''<remarks>
  '''Auto-generated field.
  '''To modify move field declaration from designer file to code-behind file.
  '''</remarks>
  Protected WithEvents A8 As Global.System.Web.UI.HtmlControls.HtmlAnchor

  '''<summary>
  '''A9 control.
  '''</summary>
  '''<remarks>
  '''Auto-generated field.
  '''To modify move field declaration from designer file to code-behind file.
  '''</remarks>
  Protected WithEvents A9 As Global.System.Web.UI.HtmlControls.HtmlAnchor

  '''<summary>
  '''A10 control.
  '''</summary>
  '''<remarks>
  '''Auto-generated field.
  '''To modify move field declaration from designer file to code-behind file.
  '''</remarks>
  Protected WithEvents A10 As Global.System.Web.UI.HtmlControls.HtmlAnchor

  '''<summary>
  '''lblNameFinancier control.
  '''</summary>
  '''<remarks>
  '''Auto-generated field.
  '''To modify move field declaration from designer file to code-behind file.
  '''</remarks>
  Protected WithEvents lblNameFinancier As Global.System.Web.UI.WebControls.Label

  '''<summary>
  '''MainContent control.
  '''</summary>
  '''<remarks>
  '''Auto-generated field.
  '''To modify move field declaration from designer file to code-behind file.
  '''</remarks>
  Protected WithEvents MainContent As Global.System.Web.UI.WebControls.ContentPlaceHolder

  '''<summary>
  '''DropDownList1 control.
  '''</summary>
  '''<remarks>
  '''Auto-generated field.
  '''To modify move field declaration from designer file to code-behind file.
  '''</remarks>
  Protected WithEvents DropDownList1 As Global.System.Web.UI.WebControls.DropDownList
End Class
