'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated from a template.
'
'     Manual changes to this file may cause unexpected behavior in your application.
'     Manual changes to this file will be overwritten if the code is regenerated.
' </auto-generated>
'------------------------------------------------------------------------------

Imports System
Imports System.Collections.Generic

Partial Public Class SURVEY
    Public Property surveyId As Integer
    Public Property firstName As String
    Public Property lastName As String
    Public Property email As String
    Public Property phone As String
    Public Property isFollowUp As Nullable(Of Boolean)
    Public Property question1Stars As Nullable(Of Integer)
    Public Property question2Stars As Nullable(Of Integer)
    Public Property question3Stars As Nullable(Of Integer)
    Public Property question4Option1 As Nullable(Of Boolean)
    Public Property question4Option2 As Nullable(Of Boolean)
    Public Property question4Option3 As Nullable(Of Boolean)
    Public Property question4Option4 As Nullable(Of Boolean)
    Public Property question4Option5 As Nullable(Of Boolean)
    Public Property question4Option6 As Nullable(Of Boolean)
    Public Property question4Option6Value As String
    Public Property question5Option1 As Nullable(Of Boolean)
    Public Property question5Option2 As Nullable(Of Boolean)
    Public Property question5Option3 As Nullable(Of Boolean)
    Public Property question5Option4 As Nullable(Of Boolean)
    Public Property question5Option5 As Nullable(Of Boolean)
    Public Property question5Option6 As Nullable(Of Boolean)
    Public Property question5Option6Value As String
    Public Property question6 As String
    Public Property question7 As String
    Public Property createdOn As Nullable(Of Date)

End Class
