'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated by a tool.
'
'     Changes to this file may cause incorrect behavior and will be lost if
'     the code is regenerated. 
' </auto-generated>
'------------------------------------------------------------------------------

Option Strict On
Option Explicit On


Partial Public Class Temp

  '''<summary>
  '''accZakat control.
  '''</summary>
  '''<remarks>
  '''Auto-generated field.
  '''To modify move field declaration from designer file to code-behind file.
  '''</remarks>
  Protected WithEvents accZakat As Global.AjaxControlToolkit.Accordion

  '''<summary>
  '''paneReply control.
  '''</summary>
  '''<remarks>
  '''Auto-generated field.
  '''To modify move field declaration from designer file to code-behind file.
  '''</remarks>
  Protected WithEvents paneReply As Global.AjaxControlToolkit.AccordionPane

  '''<summary>
  '''prgStatement control.
  '''</summary>
  '''<remarks>
  '''Auto-generated field.
  '''To modify move field declaration from designer file to code-behind file.
  '''</remarks>
  Protected WithEvents prgStatement As Global.System.Web.UI.HtmlControls.HtmlGenericControl

  '''<summary>
  '''ltlPercentStatement control.
  '''</summary>
  '''<remarks>
  '''Auto-generated field.
  '''To modify move field declaration from designer file to code-behind file.
  '''</remarks>
  Protected WithEvents ltlPercentStatement As Global.System.Web.UI.WebControls.Literal

  '''<summary>
  '''txtPersonalStatement control.
  '''</summary>
  '''<remarks>
  '''Auto-generated field.
  '''To modify move field declaration from designer file to code-behind file.
  '''</remarks>
  Protected WithEvents txtPersonalStatement As Global.System.Web.UI.WebControls.TextBox
End Class
