'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated from a template.
'
'     Manual changes to this file may cause unexpected behavior in your application.
'     Manual changes to this file will be overwritten if the code is regenerated.
' </auto-generated>
'------------------------------------------------------------------------------

Imports System
Imports System.Collections.Generic

Partial Public Class TRANSLATION
    Public Property translationId As Integer
    Public Property translationNameEnglish As String
    Public Property translationNameNative As String
    Public Property translationURL As String

End Class
