'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated from a template.
'
'     Manual changes to this file may cause unexpected behavior in your application.
'     Manual changes to this file will be overwritten if the code is regenerated.
' </auto-generated>
'------------------------------------------------------------------------------

Imports System
Imports System.Collections.Generic

Partial Public Class USER
    Public Property userId As Integer
    Public Property email As String
    Public Property password As String
    Public Property firstName As String
    Public Property middleName As String
    Public Property lastName As String
    Public Property maritalStatus As String
    Public Property dob As Nullable(Of Date)
    Public Property gender As String
    Public Property phone As String
    Public Property socialSecurityNumber As String
    Public Property street As String
    Public Property city As String
    Public Property stateAbbr As String
    Public Property zip As String
    Public Property beginResidenceDate As Nullable(Of Date)
    Public Property residenceType As String
    Public Property nationalityId As Nullable(Of Integer)
    Public Property highestEducationCompleted As String
    Public Property schoolStreet As String
    Public Property schoolCity As String
    Public Property schoolStateAbbr As String
    Public Property schoolZip As String
    Public Property totalValueCash As Nullable(Of Decimal)
    Public Property totalValueGold As Nullable(Of Decimal)
    Public Property totalValueSilver As Nullable(Of Decimal)
    Public Property totalValueInvestments As Nullable(Of Decimal)
    Public Property citizenshipStatus As String
    Public Property hasHealthInsurance As Nullable(Of Boolean)
    Public Property medicaidNumber As String
    Public Property medicareNumber As String
    Public Property healthInsuranceProviderName As String
    Public Property healthInsuranceProviderPolicyNumber As String
    Public Property hasLifeInsurance As Nullable(Of Boolean)
    Public Property hasChildSupport As Nullable(Of Boolean)
    Public Property totalMonthlyChildSupport As Nullable(Of Decimal)
    Public Property hasFoodStamps As Nullable(Of Boolean)
    Public Property totalMonthlyFoodStamps As Nullable(Of Decimal)
    Public Property hasTemporaryCashAssistance As Nullable(Of Boolean)
    Public Property totalTemporaryCashAssistance As Nullable(Of Decimal)
    Public Property sourceTemporaryCashAssistance As String
    Public Property has401KPension As Nullable(Of Boolean)
    Public Property hasEmployer As Nullable(Of Boolean)
    Public Property employerName As String
    Public Property positionTitle As String
    Public Property totalMonthlySalary As Nullable(Of Decimal)
    Public Property employmentStartDate As Nullable(Of Date)
    Public Property employerStreet As String
    Public Property employerCity As String
    Public Property employerStateAbbr As String
    Public Property employerZip As String
    Public Property employerPhone As String
    Public Property hasReference1 As Boolean
    Public Property reference1FullName As String
    Public Property reference1Email As String
    Public Property reference1Phone As String
    Public Property reference1KnownSince As Nullable(Of Date)
    Public Property reference1Relationship As String
    Public Property reference1Street As String
    Public Property reference1City As String
    Public Property reference1StateAbbr As String
    Public Property reference1Zip As String
    Public Property hasReference2 As Boolean
    Public Property reference2FullName As String
    Public Property reference2Email As String
    Public Property reference2Phone As String
    Public Property reference2KnownSince As Nullable(Of Date)
    Public Property reference2Relationship As String
    Public Property reference2Street As String
    Public Property reference2City As String
    Public Property reference2StateAbbr As String
    Public Property reference2Zip As String
    Public Property primaryMasjidName As String
    Public Property primaryMasjidPhone As String
    Public Property hasOutstandingDebts As Nullable(Of Boolean)
    Public Property totalOutstandingDebts As Nullable(Of Decimal)
    Public Property hasLoanedMoney As Nullable(Of Boolean)
    Public Property totalLoanedMoney As Nullable(Of Decimal)
    Public Property zakatReasonDescription As String
    Public Property createdOn As Nullable(Of Date)
    Public Property createdBy As Nullable(Of Integer)
    Public Property updatedOn As Nullable(Of Date)
    Public Property updatedBy As Nullable(Of Integer)

    Public Overridable Property APPLICATION As ICollection(Of APPLICATION) = New HashSet(Of APPLICATION)
    Public Overridable Property CERTIFICATION_SKILL As ICollection(Of CERTIFICATION_SKILL) = New HashSet(Of CERTIFICATION_SKILL)
    Public Overridable Property DEPDENDENT As ICollection(Of DEPDENDENT) = New HashSet(Of DEPDENDENT)
    Public Overridable Property NATIONALITY As NATIONALITY
    Public Overridable Property STATE As STATE
    Public Overridable Property USER_LANGUAGE As ICollection(Of USER_LANGUAGE) = New HashSet(Of USER_LANGUAGE)
    Public Overridable Property USER_ROLE As ICollection(Of USER_ROLE) = New HashSet(Of USER_ROLE)

End Class
