'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated from a template.
'
'     Manual changes to this file may cause unexpected behavior in your application.
'     Manual changes to this file will be overwritten if the code is regenerated.
' </auto-generated>
'------------------------------------------------------------------------------

Imports System
Imports System.Collections.Generic

Partial Public Class VW_APPLICATIONS_BY_USER_AGE
    Public Property applicationId As Integer
    Public Property userId As Integer
    Public Property isSubmitted As Nullable(Of Boolean)
    Public Property isDispersed As Nullable(Of Boolean)
    Public Property isRejected As Nullable(Of Boolean)
    Public Property Age As Nullable(Of Integer)

End Class
