'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated from a template.
'
'     Manual changes to this file may cause unexpected behavior in your application.
'     Manual changes to this file will be overwritten if the code is regenerated.
' </auto-generated>
'------------------------------------------------------------------------------

Imports System
Imports System.Collections.Generic

Partial Public Class VW_APPLICATIONS_TOTAL_DISPERSED
    Public Property applicationId As Integer
    Public Property year As Nullable(Of Integer)
    Public Property month As Nullable(Of Integer)
    Public Property dispersedAmount As Nullable(Of Decimal)

End Class
